# Generated by Django 3.2.8 on 2021-10-22 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='django.db.models.BigAutoField'),
            preserve_default=False,
        ),
    ]
